-- AlterTable
ALTER TABLE `rents` ADD COLUMN `advancePaid` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `externalPaid` DOUBLE NOT NULL DEFAULT 0,
    ADD COLUMN `paidDate` DATETIME(3) NULL,
    ADD COLUMN `paidType` VARCHAR(191) NULL,
    ADD COLUMN `previousDue` DOUBLE NOT NULL DEFAULT 0;
